AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Mutant Finder with Spring

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  MutantFinderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.meli.mutant.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: .
      MemorySize: 512
      Policies: [AWSLambdaBasicExecutionRole, AWSLambdaVPCAccessExecutionRole]
      Timeout: 30
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            TimeoutInMillis: 20000
            PayloadFormatVersion: '1.0'
      VpcConfig:
        SecurityGroupIds:
          - sg-420cec3c
        SubnetIds:
          - subnet-4ed8a502
          - subnet-33cf1058
          - subnet-b42a3fce

Outputs:
  SpringMutantFinderApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/mutant'
    Export:
      Name: SpringMutantFinderApi
